killold:
  stage: clean
  script:
   - if pgrep dotnet; then pkill dotnet; fi

testbuild:
  stage: build
  script:
    - dotnet restore
    - dotnet publish -c Release

runProject:
  stage: run
  script:
    - ls
    - rm appsettings.json
    - ls /
    - cp /appsettings.json appsettings.json
    - dotnet run
    
stages:
  - clean
  - build
  - run

