killold:
  stage: clean
  script:
   - if pgrep dotnet; then pkill dotnet; fi

runProject:
  stage: run
  script:
    - ls
    - rm appsettings.json
    - cp /appsettings.json appsettings.json
    - dotnet run

stages:
  - clean
  - run
