killold:
  stage: clean
  script:
   - rm -r /lokilogger
   - systemctl stop lokilogger

testbuild:
  stage: build
  script:
    - dotnet restore
    - dotnet publish -c Release

runProject:
  stage: run
  script:
    - mkdir /lokilogger
    - cp * /lokilogger/*
    - cd /lokilogger
    - rm appsettings.json
    - cp /appsettings.json appsettings.json
    - systemctl lokilogger start
    
stages:
  - clean
  - build
  - run