killold:
  stage: clean
  script:
   - rm -r /lokilogger ||true
   - systemctl stop lokilogger ||true

testbuild:
  stage: build
  script:
    - dotnet restore
    - dotnet publish -c Release

runProject:
  stage: run
  script:
    - mkdir /lokilogger
    - cp -r * /lokilogger
    - cd /lokilogger
    - rm appsettings.json ||true
    - cp /appsettings.json appsettings.json
    - systemctl start lokilogger 
    
stages:
  - build
  - clean
  - run