killold:
  stage: clean
  script:
   - whoami 
   - if pgrep dotnet; then pkill dotnet; fi

runProject:
  stage: run
  script:
    - cd lokiloggerreporter
    - rm appsettings.json
    - mv /appsettings.json appsettings.json
    - dotnet run

stages:
  - clean
  - run
