// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lokiloggerreporter.Models;

namespace lokiloggerreporter.Migrations
{
    [DbContext(typeof(DatabaseCtx))]
    [Migration("20191008202637_WebRequest")]
    partial class WebRequest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("lokiloggerreporter.Models.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<string>("Data");

                    b.Property<string>("Exception");

                    b.Property<int>("Line");

                    b.Property<int>("LogLevel");

                    b.Property<int>("LogTyp");

                    b.Property<string>("Message");

                    b.Property<string>("Method");

                    b.Property<string>("SourceId");

                    b.Property<int>("ThreadId");

                    b.Property<DateTime>("Time");

                    b.Property<string>("WebRequestId");

                    b.HasKey("ID");

                    b.HasIndex("SourceId");

                    b.HasIndex("WebRequestId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("lokiloggerreporter.Models.Source", b =>
                {
                    b.Property<string>("SourceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Secret");

                    b.Property<string>("Tag");

                    b.Property<string>("Version");

                    b.HasKey("SourceId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("lokiloggerreporter.Models.WebRequest", b =>
                {
                    b.Property<string>("WebRequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientIp");

                    b.Property<DateTime>("End");

                    b.Property<string>("Exception");

                    b.Property<string>("Host");

                    b.Property<string>("HttpMethod");

                    b.Property<string>("Path");

                    b.Property<string>("QueryString");

                    b.Property<string>("RequestBody");

                    b.Property<string>("ResponseBody");

                    b.Property<string>("Scheme");

                    b.Property<DateTime>("Start");

                    b.Property<int>("StatusCode");

                    b.Property<string>("TraceId");

                    b.HasKey("WebRequestId");

                    b.ToTable("WebRequest");
                });

            modelBuilder.Entity("lokiloggerreporter.Models.Log", b =>
                {
                    b.HasOne("lokiloggerreporter.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("lokiloggerreporter.Models.WebRequest", "WebRequest")
                        .WithMany()
                        .HasForeignKey("WebRequestId");
                });
#pragma warning restore 612, 618
        }
    }
}
